version: "3.9"
services:
   platformapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_DRIVER=postgres
      - DB_SOURCE=postgresql://root:secret@postgresql:5432/platform_transactions?sslmode=disable
    depends_on:
      - postgresql

   postgresql : 
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=platform_transactions