// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ArgoWorkflow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Path        string             `json:"path"`
	Description int64              `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type EnvLayer struct {
	ID               int64              `json:"id"`
	EnvironmentID    int64              `json:"environment_id"`
	S3Path           string             `json:"s3_path"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ProcessID        int64              `json:"process_id"`
	CurrentRequestID pgtype.Int8        `json:"current_request_id"`
}

type Process struct {
	ID         int64              `json:"id"`
	ArgoID     int64              `json:"argo_id"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TemplateID int64              `json:"template_id"`
}

type Project struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	GitPath     string             `json:"git_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Description pgtype.Text        `json:"description"`
}

type ProjectEnvironment struct {
	ID          int64              `json:"id"`
	GitBranch   string             `json:"git_branch"`
	ProjectID   int64              `json:"project_id"`
	Description pgtype.Text        `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Request struct {
	ID            int64              `json:"id"`
	LayerID       int64              `json:"layer_id"`
	EnvironmentID int64              `json:"environment_id"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Template struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Path string `json:"path"`
	Type string `json:"type"`
}
