// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EnvLayer struct {
	ID            int64              `json:"id"`
	EnvironmentID int64              `json:"environment_id"`
	S3Path        string             `json:"s3_path"`
	TemplateID    int64              `json:"template_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID        int64              `json:"id"`
	Message   string             `json:"message"`
	ProcessID int64              `json:"process_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Process struct {
	ID                int64              `json:"id"`
	NameOfArgoProcess string             `json:"name_of_argo_process"`
	Currentstep       string             `json:"currentstep"`
	LayerID           int64              `json:"layer_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	GitPath     string             `json:"git_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Description pgtype.Text        `json:"description"`
}

type ProjectEnvironment struct {
	ID          int64              `json:"id"`
	GitBranch   string             `json:"git_branch"`
	ProjectID   int64              `json:"project_id"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Request struct {
	ID            int64              `json:"id"`
	LayerID       int64              `json:"layer_id"`
	EnvironmentID int64              `json:"environment_id"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Template struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Path string `json:"path"`
}
