// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateArgoWorkflow(ctx context.Context, arg CreateArgoWorkflowParams) (ArgoWorkflow, error)
	CreateEnvLayer(ctx context.Context, arg CreateEnvLayerParams) (EnvLayer, error)
	CreateProcess(ctx context.Context, arg CreateProcessParams) (Process, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectEnvironment(ctx context.Context, arg CreateProjectEnvironmentParams) (ProjectEnvironment, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error)
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error)
	DeleteArgoWorkflow(ctx context.Context, id int64) error
	DeleteEnvLayer(ctx context.Context, id int64) error
	DeleteProcess(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	DeleteProjectEnvironment(ctx context.Context, id int64) error
	DeleteRequest(ctx context.Context, id int64) error
	DeleteTemplate(ctx context.Context, id int64) error
	GetArgoWorkflow(ctx context.Context, id int64) (ArgoWorkflow, error)
	GetEnvLayer(ctx context.Context, id int64) (EnvLayer, error)
	GetProcess(ctx context.Context, id int64) (Process, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetProjectEnvironment(ctx context.Context, id int64) (ProjectEnvironment, error)
	GetRequest(ctx context.Context, id int64) (Request, error)
	GetTemplate(ctx context.Context, id int64) (Template, error)
	ListArgoWorkflows(ctx context.Context, arg ListArgoWorkflowsParams) ([]ArgoWorkflow, error)
	ListEnvLayers(ctx context.Context, arg ListEnvLayersParams) ([]EnvLayer, error)
	ListProcesss(ctx context.Context, arg ListProcesssParams) ([]Process, error)
	ListProjectEnvironments(ctx context.Context, arg ListProjectEnvironmentsParams) ([]ProjectEnvironment, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListRequests(ctx context.Context, arg ListRequestsParams) ([]Request, error)
	ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]Template, error)
	UpdateArgoWorkflow(ctx context.Context, arg UpdateArgoWorkflowParams) error
	UpdateEnvLayer(ctx context.Context, arg UpdateEnvLayerParams) error
	UpdateProcess(ctx context.Context, arg UpdateProcessParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectEnvironment(ctx context.Context, arg UpdateProjectEnvironmentParams) error
	UpdateRequest(ctx context.Context, arg UpdateRequestParams) error
	UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error
}

var _ Querier = (*Queries)(nil)
