// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: test.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO project (
    name,
    git_path,
    description
) VALUES (
    $1, $2, $3
) RETURNING id, name, git_path, created_at, description
`

type CreateProjectParams struct {
	Name        string      `json:"name"`
	GitPath     string      `json:"git_path"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.GitPath, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GitPath,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}
